### ISSUE TITLE
Can a MatLab executable be made from Margo?

### ISSUE THREAD

**Issue by malcook** [de-Bivort-Lab/autotracker#40]
I am not a MATLAB expert, and am trying to advise colleagues as to whether this is possible and seek your insights and corrections to my understanding of the issues in making a standalone MATLAB executable from Margo.

To answer this, we will need to refer in part to [The following table shows the MATLAB toolboxes that you can use with MATLAB Compiler and describes which functionality can and cannot be compiled](https://www.mathworks.com/products/compiler/compiler_support.html) where we learn that, for the most part, **only command line functionality of the toolboxes can be compiled into standalones** (notably NOT UIs and Apps but also other aspects of selected toolboxes). Does Margo transgress any of these limitations (e.g. does it use UIs/Apps from the required toolboxes)? I further expect that your [preprint](https://www.biorxiv.org/content/10.1101/593046v1.full)'s observation that "Software for control of all custom electronic hardware was written in C using Arduino libraries" will bear on what is possible in this regard.  Do you agree? Finally, we only have an old compiler license - do you agree this will limit us (especially given the answer to this question: [Is it possible the use of a MCR version different from the utilized version of Matlab Compiler?](https://www.mathworks.com/matlabcentral/answers/276125-it-s-possible-the-use-of-a-mcr-version-different-from-the-utilized-version-of-matlab-compiler) ).

Thanks for your consideration.

**Comment by werkhoven** [comment]
Margo was not designed to run separately from the UI, which as you pointed out would be incompatible with building a MATLAB executable. I do think that it would hypothetically be possible to build the core tracking implementation into an executable, but that would require some substantial modification of the code. I can't however guarantee that it would since I've never really tried this and I didn't design it with that functionality in mind.

To my knowledge, interaction with serial devices would not really be affected since all the really happens on Margo's end is formatting and writing data to a port.

I hope this helps.

**Comment by malcook** [comment]
Hello Zachary,

I much appreciate your thoughtful reply to my inquiry.

I'm cc:ing those researchers on my side who may have an interest in pursuing this.  I will be sure to let you know if we pursue this line with any success.

Regards,

~ malcolm_cook@stowers.org

________________________________________
