### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by simfor** [de-Bivort-Lab/autotracker#7]
![screenshot from 2018-10-24 16-19-00](https://user-images.githubusercontent.com/767724/47673284-88afea00-db8a-11e8-92ec-37715f21c4c3.png)

**Comment by werkhoven** [comment]
This issue has been fixed in the more recent commits of `master_beta`. The issue has to do with the renaming of the GUI from autotracker to margo and resulted from a call to `autotracker` to launch the GUI rather than `margo`. The function `autotracker` has been removed from branch and should not occur anymore.
